### PR TITLE
Was going to add animation, completely rewrite extension instead

### PR DESCRIPTION
**Pull request by kyuucr**
Please test :))
- Reworked Indicator, no more two show-hide indicator!
- Changed and unified tray icon container
- Added animation for showing and hiding tray icons
- Better button behavior for tray icon
- Reworked NotificationManager as a class
- Split codes to another file
- Code cleanup

Known existing bug:
- Strange tray icon behavior from NotificationManager, icon sometimes disappear (but still retain clutter actor) when re-enabling extension, or for no reason at all, this is also a bug in TopIcon extension

### CODE REVIEW

**Comment by kyuucr** [comment]
Wow this hound bot is completely off the mark

**Comment by cldx** [comment]
Have you looked into the devel branch lately? We really need to communicate better, i did a lot of those changes already, including 'fixing' the Clutter Actor mess (which was caused by constantly throwing the Legacy Icons from Panel to Message Tray without properly removing the Actor), also i added 3.16 support already.

Whats your preferred messenger and how do i get to chat to you? So we don't waste our energy on doing things twice.

**Comment by cldx** [comment]
And yeah, this bot is completely off the hook, can we get rid of it?

**Comment by kyuucr** [comment]
@cldx haha really sorry, the thing is I'm in a sort of coding trance today, and I'm completely forgot to check other branch. You can contact me through google talk or gmail, so now we will combine our code? 
I think apart from things that you already done, my contribution is only on adding show/hide animation for tray icon. To do that I decouple the tray container from panel and put it on root UI instead, so it can be tween easily.
Other little thing is just making the button behavior nicer, the old tray icon has this weird behavior where you can only click the center of the icon, and when the icon is hovered, the button is not, so I fix that to make the button and icon work more integrally like a single button.
And for houndci I think only the one who enables it could disable it, or not? This is their website https://houndci.com/, there's a github sign in button and I don't want to sign it up since it will be a hassle if it shows up in my codes.

**Comment by satya164** [comment]
I'll add configs for hound and tell it to support ES6, so that const, let etc are supported, and it won't give warnings about naming.

**Pull request closed without merging**
